theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
# render = true
# skip-levels = 1

[editor.soft-wrap]
enable = true
wrap-indicator = ""
